repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  # Stop commits to master
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0  # Use the ref you want to point at
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master] 
      - id: check-merge-conflict
        stages: [commit] 

  - repo: local
    hooks:

    # Run the code linter when you commit, but only if javascript files are changed
    - id: lint
      name: lint
      language: system
      stages: [commit, push]
      verbose: true
      entry: sh -c "NODE_ENV=ci npm run lint"
      types: [file, javascript]
      pass_filenames: false

    - id: unit-tests
      name: Run unit tests
      language: system
      stages: [push]
      verbose: true
      entry: sh -c "NODE_ENV=ci npm run test"
      pass_filenames: false
